Importing Numpy

In [1]:
import numpy as np

Arrays

In [46]:
# One Dimensional Array
t=np.array([1,2,3])
print(t)
# Two Dimensional Array
t=np.array([(1,2,3),(3,4,5)])
print(t)
#Three Dimensional Array
t= np.array([
    [[1, 2,3],
        [4, 5, 6]],
    [[7, 8,9],
        [10, 11, 12]]
])
print(t)

[1 2 3]
[[1 2 3]
 [3 4 5]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


Matrices

In [ ]:
#Null Matrix or Zero Matrix
t=np.zeros((4,5))
print(t)
#Ones Matrix
t=np.ones((5,6))
print(t)
#Unit Matrix
t=np.eye(4)
print(t)
#Diagonal Matrix
t=np.diag([1,2,3,4])
print(t)

Random Numbers

In [48]:
#To get Random Integer values in a Range
t=np.random.randint(1,15,4)
print(t)
#To get Random Values with deviation
t=np.random.normal(1,0.2,4)
print(t)
#To get same Value using Random by making Use of Seed COmmand
np.random.seed(5)
t=np.random.randint(1,100) #random integer gets stored in t which is in between 1 and 100
np.random.seed(5)          #Since same seed Value of 5 is used here as Above
x=np.random.randint(1,100) #Same integer is stored in x as in t
print(t)
print(x)
#To get a Random Number between 0 and 1
t=np.random.rand()
print(t)

[14  7  7  1]
[0.6688613  0.7655694  1.05388115 0.99853315]
79
79
0.8707323061773764


Arange and Reshape Functions

In [3]:
t=np.arange(0,9).reshape(3,3)
#Here arange(0,9) stores the values from 0 to 8
#Reshape(3,3) changes the array into a 3x3 matrix
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Size and Shape Functions

In [50]:
t=np.arange(0,9).reshape(3,3)
print(t.size)#shows the number of elements in t
print(t.shape)#shows the shape of t

9
(3, 3)


LinSpace and LogSpace Functions

In [63]:
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [64]:
np.logspace(1,5,num=5,endpoint=False)

array([1.00000000e+01, 6.30957344e+01, 3.98107171e+02, 2.51188643e+03,
       1.58489319e+04])

Dot Product

In [66]:
t=np.array([1,2])
s=np.array([3,4])
print(np.dot(t,s))#Multiplies Elements with Corresponding index and adds the product to find sum

11


Concatenate

In [71]:
t=np.array([[1,2],[3,4]])
s=np.array([[4,5]])
z=np.concatenate((t,s))
print(z)

[[1 2]
 [3 4]
 [4 5]]


Fix and Rint Functions

In [81]:
#Fix Rounds off the number to nearest Integer towards Zero
t=[0.23,1.59,1.2,1.26,9.99]
print(np.fix(t))
#Rint Rounds off the number to nearest integer
print(np.rint(t))

[0. 1. 1. 1. 9.]
[ 0.  2.  1.  1. 10.]


Sort and Transpose Function

In [82]:
#Sorts each element in ascending order
t=np.array([[5,6,2],[9,8,1]])
print(np.sort(t))
#Interchanges the Row and Column positions of the Elements
print(np.transpose(t))

[[2 5 6]
 [1 8 9]]
[[5 9]
 [6 8]
 [2 1]]


Append Function

In [4]:
t=np.array([[5,6,2],[9,8,1]])
print(np.rint(t))
t=np.append(t,[1,2,3])
print(t)

[[5. 6. 2.]
 [9. 8. 1.]]
[5 6 2 9 8 1 1 2 3]


Stack Functions

In [86]:
t=np.array([1,2,3])
s=np.array([4,5,6])
#Horizontal Stack
print(np.hstack([t,s]))
#Vertical Stack
print(np.vstack([t,s]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


where function

In [99]:
t=np.array([1,2,13,14,55,16,22,17,20,13,19])
s=np.where(t%2==1,5,t)#Replaces all odd numbers as 5 by finding the indices using where
print(s)
print(np.where(t%2==0))#returns the index of the elements which are even

[ 5  2  5 14  5 16 22  5 20  5  5]
(array([1, 3, 5, 6, 8], dtype=int64),)


Common Terms in Two arrays

In [92]:
t=np.arange(10)
s=np.array([1,13,4,6,8,20,56])
print(np.intersect1d(t,s))

[1 4 6 8]


Removing Elements of one array from another

In [95]:
t=np.arange(10)
s=np.array([1,13,4,6,8,20,56])
print(np.setdiff1d(t,s))
print(np.setdiff1d(s,t))

[0 2 3 5 7 9]
[13 20 56]


Swapping Columns in a Two Dimensional Array

In [105]:
t=np.arange(0,9).reshape(3,3)
print(t)
t=t[:,[1,0,2]]
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1 0 2]
 [4 3 5]
 [7 6 8]]


Swapping Rows in a Two Dimensional Array

In [106]:
t=np.arange(0,9).reshape(3,3)
print(t)
t=t[[1,0,2],:]
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


e[r,c]
e[2]

Reversing Rows/Columns in a Matrix

In [110]:
#Reversing Rows
t=np.arange(0,9).reshape(3,3)
print(t)
print("Matrix with Reversed Rows")
print(t[::-1])
#Reversing Columns
t=t[:,::-1]
print("Matrix with reversed Columns")
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Matrix with Reversed Rows
[[6 7 8]
 [3 4 5]
 [0 1 2]]
Matrix with reversed Columns
[[2 1 0]
 [5 4 3]
 [8 7 6]]


Using Print Options Commands

In [207]:
#Specifying the number of decimal Places
t=np.random.normal(5,0.5,5)
np.set_printoptions(precision=3)#precision=3 specifies only 3 decimal places
print(t)

#Giving Output Using Scientific Notations
np.set_printoptions(suppress=False)#Setting printoptions to default
t=np.random.normal(15,0.2,3)/1e6
print(t)

#Limiting The Number of Elements Printed
np.set_printoptions(suppress=False)
np.set_printoptions(threshold=3)
t=np.random.normal(15,0.6,9)
print(t)

[6.017 4.993 4.975 5.203 4.477]
[1.484e-05 1.484e-05 1.473e-05]
[15.867 14.624 16.045 ... 15.015 14.681 14.912]


In [9]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
p=a[0, :]
print(p)

[ 3 10]


In [10]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
p=a[:,2]
print(p)

[ 3 10]


In [19]:
t=input()
rev=t[3::1]
print(rev)

hin
